### ISSUE TITLE
Params disappear

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#776] opened 2015-03-29 13:06 UTC
* create two param bars
  * add a vector or quaternion to one of them
  * open the vector or quaternion group
  * click on the other bar
  * the contents of the clicked bar disappear

test app:
https://gist.github.com/gaborpapp/2960f3cc198ed0b71af3

glNext in OS X 10.9

![screen shot 2015-03-29 at 15 03 45](https://cloud.githubusercontent.com/assets/203532/6885544/f08ae5c2-d624-11e4-818b-27359ee9eb8c.png)

**Comment by richardeakin** [comment] 2015-04-02 14:44
Confirmed. This looks like some ATB internal state issue.. not fun.

**Comment by gaborpapp** [comment] 2015-04-02 14:49
It might be an ATB issue, but this is not happening in 0.8.6.

**Comment by lithium-snepo** [comment] 2015-04-04 03:53
Standalone application using glfw doesn't replicate the issue.
https://gist.github.com/lithium-snepo/bfe213f045f973dfc577

**Comment by lithium-snepo** [comment] 2015-04-04 07:03
Tracked down this issue to this commit: https://github.com/cinder/Cinder/commit/2cc21c719f8d833d7c8615ddb744785b69732140

Recompiling cinder with the TwOpenGLCore.cpp version prior to this commit fixes the problem.

**Comment by gaborpapp** [comment] 2015-04-04 15:58
Switching back with TwOpenGLCore.cpp indeed works. Thanks. I found that enabling the commented out parts in https://github.com/cinder/Cinder/blob/glNext/src/AntTweakBar/TwOpenGLCore.cpp#L896 and https://github.com/cinder/Cinder/blob/glNext/src/AntTweakBar/TwOpenGLCore.cpp#L932 fixes this.

**Comment by andrewfb** [comment] 2015-04-04 20:55
Thanks for the hunting and reproducible case - should be fixed by 89298019221cbe24d2a4f2706bedb8a88fea0acb

**Closed by andrewfb** 2015-04-04 20:55 UTC
Labels: bug, glnext

**Comment by gaborpapp** [comment] 2015-04-05 08:24
Thanks!
