### ISSUE TITLE
NormalMapping sample broken

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#948] opened 2015-05-29 10:12 UTC
The output is black only showing the emissive parts of the model. It was working a while ago, some changes probably broke it recently. OS X 10.9, NVidia 750M/Intel HD4000.

![screen shot 2015-05-29 at 12 00 12](https://cloud.githubusercontent.com/assets/203532/7880609/75311c5a-05fb-11e5-964a-b25b7e3ae897.png)

**Comment by paulhoux** [comment] 2015-05-29 18:22
Thanks for reporting, will look at it this weekend. If you find a solution yourself, let me know.

**Comment by paulhoux** [comment] 2015-05-31 18:02
Caused by the changes to glslProg. The sample sets the following uniform: 
```mShaderNormalMapping->uniform( "uLights[0].diffuse", mLightLantern.diffuse );```

, but apparently this is no longer supported. Will try to find a fix.

**Comment by paulhoux** [comment] 2015-05-31 18:18
@andrewfb  and @notlion  : the support for array brackets in uniform names does not allow accessing the ```diffuse` member of my struct. I've pushed a solution that fixes the sample, but I'm not sure what you guys were trying to fix. Could you go over it? You can find the pull request here: #951

**Comment by gaborpapp** [comment] 2015-05-31 18:20
Thanks for hunting this down. I checked the console for uniform errors, but nothing was printed, so I assumed they were set properly.

**Comment by andrewfb** [comment] 2015-06-01 18:27
This should be fixed and merged.

**Closed by andrewfb** 2015-06-01 18:27 UTC
Labels: bug, glnext
