### ISSUE TITLE
getSaveFilePath() dialog resolves to background window when in fullscreen mode.

### ISSUE THREAD

**Issue by wildparadox** [cinder/Cinder#960] opened 2015-06-02 19:57 UTC
On Osx 10.10.2, when an application is in full screen mode and getSaveFilePath() is called, the dialog will resolve to the application's blank background window if you choose to overwrite a file.

This issue is does not occur if you select a file path that does not already exist.

**Comment by andrewfb** [comment] 2015-06-03 02:23
Thanks for the report - is this against master or against glNext?

**Comment by wildparadox** [comment] 2015-06-03 02:40
Sorry this is in the glNext branch.

**Comment by andrewfb** [comment] 2015-06-07 03:49
Just confirming that I can repro this on both 10.10 and 10.9.5. This looks pretty low-level and is going to take some work to track down. For those Cocoa experts who are up to try to repro this:

```C++
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"
#include "cinder/ImageIo.h"

using namespace ci;
using namespace ci::app;
using namespace std;

class TestApp : public App {
  public:
	void keyDown( KeyEvent event ) override;
	void draw() override;
};

void TestApp::keyDown( KeyEvent event )
{
	if( event.getChar() == 's' ) {
		fs::path path = getSaveFilePath();
		if( ! path.empty() ) {
			Surface s8( 640, 480, false );
			writeImage( writeFile( path ), s8 );
		}
	}
}

void TestApp::draw()
{
	gl::clear( Color( 0.5f, 0.5f, 0.5f ) );
}

CINDER_APP( TestApp, RendererGl, []( App::Settings *settings ) {
	settings->setFullScreen();
} )
```

Hit 's', save an image, and then 's' again and choose to overwrite the same path. A mysterious new window appears and the fullscreen one remains.

**Comment by pizthewiz** [comment] 2015-06-07 19:09
This also reproduces on OS X 10.10.4 and Xcode 6.4.

Probably just restating what is already known but: If I had to make a snap guess, I'd say some state is changed in the overwrite sheet that pokes at a nonexistent window and causes a new one to be created.
<img src="http://i.imgur.com/8p26zzO.png" width="536" height="304">

Also interesting, the app crashes when the mystery window is closed:
```gdb
(lldb) bt
* thread #1: tid = 0x58c3d6, 0x0000000100194430 SaveApp`cinder::app::Window::testValid(this=0x0000000000000000) const + 16 at Window.h:448, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
  * frame #0: 0x0000000100194430 SaveApp`cinder::app::Window::testValid(this=0x0000000000000000) const + 16 at Window.h:448
    frame #1: 0x00000001000ac167 SaveApp`cinder::app::Window::getRenderer(this=0x0000000000000000) const + 39 at Window.cpp:248
    frame #2: 0x00000001000ac96b SaveApp`cinder::app::Window::emitMouseMove(this=0x0000000000000000, event=0x00007fff5fbfecd8) + 43 at Window.cpp:346
    frame #3: 0x000000010001b0ea SaveApp`-[WindowImplBasicCocoa mouseMove:](self=0x00006100000a0780, _cmd=0x00000001001c7563, event=0x00007fff5fbfecd8) + 138 at AppImplMac.mm:720
    frame #4: 0x000000010006f5e4 SaveApp`-[CinderViewMac mouseMoved:](self=0x00006080001e0500, _cmd=0x00007fff9218df43, theEvent=0x0000610000120280) + 724 at CinderViewMac.mm:379
    frame #5: 0x00007fff91f73f22 AppKit`-[NSWindow _reallySendEvent:isDelayedEvent:] + 4931
    frame #6: 0x00007fff91905d66 AppKit`-[NSWindow sendEvent:] + 470
    frame #7: 0x00007fff91901da6 AppKit`-[NSApplication sendEvent:] + 1148
    frame #8: 0x00007fff9182bc48 AppKit`-[NSApplication run] + 711
    frame #9: 0x000000010009ac09 SaveApp`cinder::app::AppMac::launch(this=0x0000000102800870) + 57 at AppMac.cpp:51
    frame #10: 0x000000010001530e SaveApp`cinder::app::AppBase::executeLaunch(this=0x0000000102800870) + 30 at AppBase.cpp:137
    frame #11: 0x0000000100003ec7 SaveApp`void cinder::app::AppMac::main<TestApp>(defaultRenderer=0x00007fff5fbff8a0, title=0x00000001001b3670, argc=3, argv=0x00007fff5fbff928, settingsFn=0x00007fff5fbff8c0)> const&) + 295 at AppMac.h:93
    frame #12: 0x00000001000021ba SaveApp`main(argc=3, argv=0x00007fff5fbff928) + 218 at TestApp.cpp:32
    frame #13: 0x00007fff8c1705c9 libdyld.dylib`start + 1
    frame #14: 0x00007fff8c1705c9 libdyld.dylib`start + 1
```

**Comment by andrewfb** [comment] 2015-06-08 19:13
Just a small update. One, a more direct path to manifesting this issue is just to hit Cmd ~; it seems there's always 2 windows up when in fullscreen. I confirmed this is actually true on 0.8.6 as well. Also Rich found that the size of this spare window is the same size as the initially created Cinder window.

**Comment by pizthewiz** [comment] 2015-06-08 19:30
Good find, does this occur with both fullscreen modes, Kiosk and the other `-[NSWindow toggleFullScreen:]`?

**Comment by gaborpapp** [comment] 2015-06-09 10:16
I think this was also reported and discussed on the forum about a year ago: https://forum.libcinder.org/topic/extra-blank-window-hiding-behind-main-window-in-default-fullscreen-mode

**Comment by andrewfb** [comment] 2015-06-10 15:37
OK - I'm proposing #976 as a fix for this. From what I can tell, at least in 10.9 and 10.10, `[NSView enterFullScreen]` does not close the window it is called from, instead creating a new window. I am confirming this with `[[[NSApplication sharedApplication] windows] count]` (which is 2) as well. The issue seems to be that when an open/save dialog comes up, and then a child of that dialog is created (say by clicking the New Folder button), the window order is affected and our "old" pre-fullscreen window is brought to the foreground.

My solution is to force the non-fullscreen window to the background using `orderBack`. In addition, we needed to prevent window cycling, which we're now doing with `setCollectionBehavior`. Finally, a similar problem can manifest when the user alt-tabs away from the app, so we test for when the app regains focus and make the same `orderBack` move.

This is obviously somewhat hacky, though from my current understanding of the problem it appears to be an OS X bug to me. Additionally, the same kind of problem can manifest if you using FullScreenOptions to force fullscreen on a display other than the one the Window is currently on. There are various user-level workarounds that could be employed for this though, so for the time being I'm leaving that edge case alone.

**Comment by andrewfb** [comment] 2015-06-19 21:11
OK - I believe this is fixed now via #976. Closing this out.

**Closed by andrewfb** 2015-06-19 21:11 UTC
