### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): Invalid uniform offsets calculated for velocity::ciBlock1T member variables

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1376] opened 2016-03-09 16:55 UTC
For the velocity.frag's ciBlock1T, the application uses the following member offsets:

![image](https://cloud.githubusercontent.com/assets/9154207/13643118/94c8e5d4-e61f-11e5-8c83-3b46bbf64233.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13643096/7835c220-e61f-11e5-8499-cbad388b1885.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13643108/8516bbb6-e61f-11e5-981d-7fa3235e5241.png)

The offset, as calculated for uTimeDelta, is incorrect - it should be aligned on 16-byte boundary, since according to std140 layout rules:

```
If the member is a three-component vector with components consuming N basic machine units, the base alignment is 4N.
```

whereas 44%16 != 0

**Comment by chaoticbob** [comment] 2016-03-10 08:51
Urgh. This is bizarre. Hopefully not a bug in glslang.

**Comment by chaoticbob** [comment] 2016-03-13 04:05
Looks like glslang bug. Looking into it.

**Comment by DominikWitczakAMD** [comment] 2016-03-15 10:06
Is this something we could have a work-around for? This issue is a show-stopper before I can continue investigating the corruption in the Fish Tornado app.

**Comment by chaoticbob** [comment] 2016-03-16 06:34
Of course. Done! https://github.com/cinder/Cinder/commit/d98ff1bc3bcdeb658e6ac451503d474a0d31b58d

I checked to make sure that uTimeDelta landed on 48 as expected. And the two that follow it are 52 and 56.

**Comment by DominikWitczakAMD** [comment] 2016-04-04 10:18
According to Jon's explanation, it seems like this time it was my misunderstanding of the std140 layout rules then.. Apologies, can you back that change out, please?

**Comment by chaoticbob** [comment] 2016-04-28 18:56
I'll revert this soon.

**Closed by chaoticbob** 2016-04-28 18:56 UTC
Labels: vulkan
