### ISSUE TITLE
 app dialogs destroy gl context

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#738] opened 2015-03-12 11:24 UTC
I have encountered an issue with file dialogs in glNext (haven't tested with the new app_refactor) on OS X. When I call `app::getSaveFilePath` the gl context seems to be destoyed. I could prevent this by surrounding the dialog call with `auto prevCtx = gl::context();` and `prevCtx->makeCurrent();`. I'm not sure if this behaviour is expected or should be fixed.

**Comment by andrewfb** [comment] 2015-03-12 13:04
Can you see if you can reproduce the issue with the latest glNext? This code was recently modified. The behavior you're describing wouldn't be the expected behavior.

**Comment by pizthewiz** [comment] 2015-03-12 16:02
In case it is helpful, something similar occurred in openFrameworks and the workaround seemed to be to hold onto a reference before presenting the dialogue, see openframeworks/openFrameworks#3348

**Comment by gaborpapp** [comment] 2015-03-13 22:48
Tested with the latest glNext, and the issue persists with multiple windows. Here's a test app: https://gist.github.com/gaborpapp/3ca9939f54a12c8ced6e

**Comment by andrewfb** [comment] 2015-03-20 22:11
OK - this should be fixed now in glNext. Thanks for the test case. The problem was pretty deep, and was due primarily to modal dialogs still issuing our timerFired: callback in certain scenarios. Additionally it prompted me to do some investigating on cases where the GL Context can change out from underneath the app, defeating our active context caching. This can happen in multiwindow scenarios in particular, so now we are forcing the active GL context before drawing. This appears to be cheap on the Mac, but expensive on Windows, so we only do it on the former.

**Closed by andrewfb** 2015-03-20 22:11 UTC
Labels: bug
