### ISSUE TITLE
Loggers: need setLocationEnabled(false)

### ISSUE THREAD

**Issue by MattijsKneppers** [cinder/Cinder#1152] opened 2015-10-05 09:56 UTC
The new logging system looks great, but after replacing all my custom logging calls with the new macros, my console was very cluttered because of all the location info.

Although the location info is a great feature, it would be good if there were a way to disable it on a Logger.

**Comment by lucasvickers** [comment] 2015-10-05 13:12
Related to #572

**Comment by richardeakin** [comment] 2015-10-05 19:55
Thanks for the feedback, going to close as duplicate of #572.

**Closed by richardeakin** 2015-10-05 19:55 UTC
