### ISSUE TITLE
Docs search field focuses when any key is pressed

### ISSUE THREAD

**Issue by wdlindmeier** [cinder/Cinder#1201] opened 2015-11-28 16:55 UTC
Whenever a key is pressed on the docs website, the page scrolls to the top and focuses on the search field. This includes the (mac) command key, which makes copying anything to the clipboard impossible, and generally frustrating because you lose your place in the page.

**Comment by drewish** [comment] 2015-11-28 21:25
I think this is a duplicate of https://github.com/cinder/Cinder/issues/1154 which was closed but is definitely not fixed.

**Comment by wdlindmeier** [comment] 2015-11-29 00:05
@drewish Yep, definitely looks like the same bug. Thanks.

**Closed** 2015-11-29 00:06 UTC
